### ISSUE TITLE
How can i set channels ratios for CR ?

### ISSUE THREAD

**Issue by zlheos** [yihui-he/channel-pruning#30]
I your paper 4.1.2 section:
< Remaining channels ratios for shallow layers (conv1_x to conv3_x) and deep layers (conv4_x)
is 1 : 1:5. conv5_x are not pruned>
I set 3.0 rations for shollow layers and 1.5 rations for conv4_x, but the accuracy drop 0.77
Can  you tell me how can i set channel rations ?

**Comment by yihui-he** [comment]
you can see this post: https://github.com/yihui-he/channel-pruning/wiki/ResNet-perserving-ratio
set up ratio for VGG-16 is similar with ResNet

**Comment by zlheos** [comment]
In your channel_pruning.prototxt
{layer      channels
conv1_1	24	
conv1_2	22	
conv2_1	41
conv2_2	51
conv3_1	108
conv3_2	89
conv3_3	111
conv4_1	184
conv4_2	276
conv4_3	228
}
how can you set these layer channels?

**Comment by yihui-he** [comment]
as in paper,  1：1.5 preserving channels ratio

**Comment by slothkong** [comment]
So the ratio between Original number of feature maps is 1:1.5 , which is equivalent to 2:3.
For example, for conv1_1 we originally have 64 feature maps. Then we have that the total number of parts is 2+3 = 5. Then 1 part of 64 is : 64/5 = 12.8 . So after pruning, we should gave 2 parts of the original number of feature maps, that is: 2*12.8 = 25.6 channels. Correct?  Down is calculated for all layers...
------------------------------------------------------------------
Layer		Original	        Pruned	According to 1:1.5 ratio
conv1_1 	        64			24		25.6
conv1_2 	        64			22		25.6
conv2_1 	        128			41		51.2
conv2_2		128			51		51.2
conv3_1		256			108		102.4
conv3_2		256			89		102.4
conv3_3		256			111		102.4
conv4_1		512			184		204.8
conv4_2		512			276		204.8
conv4_3		512			228		204.8
---------------------------------------------------------------
Since the number of remaining channels you chose do not match this calculation, could you tell us if there is any particular reason for your selection? Is it based on your experimentation?

**Comment by yihui-he** [comment]
Not correct. you can see this post: https://github.com/yihui-he/channel-pruning/wiki/ResNet-perserving-ratio set up ratio for VGG-16 is similar with ResNet
